### PR TITLE
Add Kenbak-1

### PR DESCRIPTION
**Pull request by BigEd**

### CODE REVIEW

**Comment by fcambus** [comment]
Merged, thanks :)

**Comment by BigEd** [comment]
Just when you thought the list was complete...!

**Comment by fcambus** [comment]
I sure hope the list is not complete, not all platforms are covered yet ;-)

**Comment by BigEd** [comment]
I was thinking of prompting you to make a new blog post, and/or update your old one, when the list becomes stable... but it hasn't yet become stable. Although I think we are slowing down.

**Comment by fcambus** [comment]
Good call indeed. Just updated the current one, it took longer than expected as I've been transitioning to using my own custom static site generator.

Thanks for the reminder :)

**Pull request merged**
