### PR TITLE
Add HP-35 calculator emulators

### PR DESCRIPTION
**Pull request by BigEd**
Two very different approaches to this classic and revolutionary scientific calculator from 1972.

### CODE REVIEW

**Comment by fcambus** [comment]
Merged, thanks! I'm now considering adding a calculator section :)

**Comment by BigEd** [comment]
I can help with some links:

From 1972's HP-35 to 1975's HP-55, by way of the HP-45, HP-80 and HP-65. By Francois Roulet
http://home.citycable.ch/pierrefleur/HP-Classic/HP-Classic.html

Nice little hack by Hans Klaver - an HP35 in your browser with an LED to show that all is well. If you overflow the four-level stack at any point, the LED will be off.
http://hansklav.home.xs4all.nl/rpn/hp35sos.html

http://members.aon.at/nkehrer/hp45_js/hp45.html

https://epxx.co/ctb/hp11c.html

https://epxx.co/ctb/hp12c-platinum.html

http://hp15c.com/web/hp15c.html

https://epxx.co/ctb/hp16c.html

There was an HP-25 but it seems to have been lost. For the record:
http://mysite.verizon.net/vze17cymb/id13.html with a mobile version at http://mysite.verizon.net/vze17cymb/hp25emu.html

**Comment by BigEd** [comment]
Do the above look good to you for the new section? I can cook up a pull request. I'd like somehow to distinguish workalikes from microcode level emulators - ideas welcome.

**Comment by fcambus** [comment]
Just checked everything and yes, everything looks good to me. Please open a pull request, I'll definitely merge this.

Regarding your question, it could maybe be solved by adding subsections in the calculator section?

**Pull request merged**
