### PR TITLE
Removed broken links

### PR DESCRIPTION
**Pull request by simon-paris**
I tried them all. JS-VBA-M is still up, but it sends `Content-Disposition: download`, so it does not work.

### CODE REVIEW

**Comment by BigEd** [comment]
I don't think we should remove dead links - certainly we should first try to find the same project in new locations, or archived versions, or other forks of the same code. Finally, we should mark dead links as dead links.
One of these does, I think, exist as source at
https://github.com/rjanicek/vice.js

**Comment by BigEd** [comment]
pdp11-js is alive at
http://takahirox.github.io/pdp11-js/unixv6.html
with source at
https://github.com/takahirox/pdp11-js

**Comment by BigEd** [comment]
For the RISC-V angel simulator, the link has indeed rotted although the source repo is still there. I've forked it and now have a live version at
https://biged.github.io/riscv-angel/run.html

**Comment by fcambus** [comment]
Thanks to both of you for reporting the issues and proposing solutions. It appears that VICE.js and Angel are back online, and I updated links to the Basic MIPS functional simulator and pdp11-js.

For JS-VBA-M I think it made sense to delete it as there is no source published and it's been broken for months. And we now have a replacement :D

**Comment by fcambus** [comment]
I noticed some more dead links so I will try to find potential new locations and delete them if they are indeed abandoned.

**Pull request closed without merging**
